## servlet configuration
server:
  port: ${PORT:8082}

## application configuration
spring:
  application:
    name: ${APPLICATION_NAME:ignite-tuition-service}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/tuition_db?createDatabaseIfNotExist=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PWD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  ## configure active profiles
  # profiles:
  #   active: prod

## eureka server configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

# oauth2 security configuration
security:
  oauth2:
    resource:
      token-info-uri: http://${API_GW_HOST:localhost}:${API_GW_PORT:8080}/ignite-auth-service/oauth/check_token
    client:
      client-id: ignite-client
      client-secret: 1234

# oauth2 resource server configuration
oauth:
  resource-id: ${RESOURCE_ID:ignite_tuition}

## logging level
logging:
  level:
    com.swivel.ignite.tuition: ${LOG_LEVEL:DEBUG}

## Payment-Microservice
payment:
  baseUrl: http://${API_GW_HOST:localhost}:${API_GW_PORT:8080}/ignite-payment-service
  deleteByTuitionIdUrl: /api/v1/payment/delete/all/tuition/{tuitionId}

## Student-Microservice
student:
  baseUrl: http://${API_GW_HOST:localhost}:${API_GW_PORT:8080}/ignite-student-service
  findByIdUrl: /api/v1/student/get/{studentId}
  addTuitionToStudentUrl: /api/v1/student/add/student/{studentId}/tuition/{tuitionId}
  removeTuitionFromStudentUrl: /api/v1/student/remove/student/{studentId}/tuition/{tuitionId}
