# Ignite auth service deployment config
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: mohamednawaz/ignite-auth:latest
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: mysql-host
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: mysql-port
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: MYSQL_ROOT_USER
            - name: MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: MYSQL_ROOT_PASSWORD
            - name: EUREKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: eureka-host
            - name: EUREKA_PORT
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: eureka-port
            - name: API_GW_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: api-gateway-host
            - name: API_GW_PORT
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: api-gateway-port
            - name: AUTH_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: auth-host
            - name: AUTH_PORT
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: auth-port

# Cluster IP config
---
apiVersion: v1
kind: Service
metadata:
  name: auth-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: auth
      port: 8079
      targetPort: 8079