apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
data:
  # elasticsearch server
  elasticsearch-url: http://elasticsearch-clusterip-srv.default.svc.cluster.local:9200
  jvm-options: -Xmx256m -Xms256m
  discovery-type: single-node

  # logstash server
  jvm-settings: -Xmx256m -Xms256m

  # mysql server
  mysql-host: mysql-clusterip-srv.default.svc.cluster.local
  mysql-port: "3306"

  # discover server
  eureka-host: discovery-clusterip-srv.default.svc.cluster.local
  eureka-port: "8761"

  # api-gateway server
  api-gateway-host: api-gateway-clusterip-srv.default.svc.cluster.local
  api-gateway-port: "8080"

  # auth server
  auth-host: auth-clusterip-srv.default.svc.cluster.local
  auth-port: "8079"