# Logstash server deployment config
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: logstash:7.6.2
          ports:
            - name: logstash
              containerPort: 9600
            - name: lgstsh-it-lr
              containerPort: 5000
          env:
            - name: LS_JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: jvm-settings
          volumeMounts:
            - name: logstash-conf
              mountPath: /usr/share/logstash/pipeline
            - name: logstash-yml
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
      volumes:
        - name: logstash-conf
          configMap:
            name: logstash-config-map
            items:
              - key: logstash.conf
                path: logstash.conf
        - name: logstash-yml
          configMap:
            name: logstash-config-map
            items:
              - key: logstash.yml
                path: logstash.yml

# Cluster IP config
---
apiVersion: v1
kind: Service
metadata:
  name: logstash-clusterip-srv
spec:
  type: ClusterIP
  selector:
    # 'logstash-deploy' app pointer
    app: logstash
  ports:
    - name: logstash
      protocol: TCP
      port: 9600
      targetPort: 9600
    - name: lgstsh-it-lr
      protocol: TCP
      port: 5000
      targetPort: 5000
