apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config-map
data:
  logstash.conf: |-
    input {
      tcp {
        port => 5000
        codec => json
      }
    }


    output {
      elasticsearch {
        hosts => ["http://elasticsearch-clusterip-srv.default.svc.cluster.local:9200"]
        index => "logstash-%{appName}"
      }
    }
  logstash.yml: |-
    http.host: "0.0.0.0"
    xpack.monitoring.enabled: true
    xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch-clusterip-srv.default.svc.cluster.local:9200" ]
