# Ignite student service deployment config
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student
  template:
    metadata:
      labels:
        app: student
    spec:
      containers:
        - name: student
          image: mohamednawaz/ignite-student:latest
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: mysql-host
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: mysql-port
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: MYSQL_ROOT_USER
            - name: MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: MYSQL_ROOT_PASSWORD
            - name: EUREKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: eureka-host
            - name: EUREKA_PORT
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: eureka-port
            - name: API_GW_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: api-gateway-host
            - name: API_GW_PORT
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: api-gateway-port

# Cluster IP config
---
apiVersion: v1
kind: Service
metadata:
  name: student-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: student
  ports:
    - name: student
      port: 8081
      targetPort: 8081