## servlet configuration
server:
  port: ${PORT:8079}

## application configuration
spring:
  application:
    name: ${APPLICATION_NAME:ignite-auth-service}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/auth_db?createDatabaseIfNotExist=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PWD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: ${MYSQL_USER:root}
    password: ${MYSQL_PWD:password}
    baseline-version: 0
    baseline-description: "init db migration"

    # active profile should be activated for different env
  # profiles:
  #   active: prod

## eureka server configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/


## oauth2 security configuration
security:
  oauth2:
    resource:
      token-info-uri: http://${API_GW_HOST:localhost}:${API_GW_PORT:8080}/ignite-auth-service/oauth/check_token
    client:
      client-id: ignite-client
      client-secret: 1234
    link: http://${AUTH_HOST:localhost}:${AUTH_PORT:8079}

# oauth2 resource server configuration
oauth:
  resource-id: ${RESOURCE_ID:ignite_auth}

## logging level
logging:
  level:
    com.swivel.ignite.auth: ${LOG_LEVEL:DEBUG}
  file:
    path: ${LOGPATH:D:\Swivel_Projects\Ignite\Project 1\backend\ignite-auth\logs}
