## servlet configuration
server:
  port: ${PORT:8081}

## application configuration
spring:
  application:
    name: ${APPLICATION_NAME:ignite-student-service}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/student_db?createDatabaseIfNotExist=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PWD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  ## configure active profiles
  # profiles:
  #   active: prod

## eureka server configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

# oauth2 security configuration
security:
  oauth2:
    resource:
      token-info-uri: http://${API_GW_HOST:localhost}:${API_GW_PORT:8080}/ignite-auth-service/oauth/check_token
    client:
      client-id: ignite-client
      client-secret: 1234

# oauth2 resource server configuration
oauth:
  resource-id: ${RESOURCE_ID:ignite_student}

## logging level
logging:
  level:
    com.swivel.ignite.student: ${LOG_LEVEL:DEBUG}
  file:
    path: ${LOGPATH:D:\Swivel_Projects\Ignite\Project 1\backend\ignite-student\logs}

## Payment-Microservice
payment:
  baseUrl: http://${API_GW_HOST:localhost}:${API_GW_PORT:8080}/ignite-payment-service
  deleteByStudentIdUrl: /api/v1/payment/delete/all/student/{studentId}

## Tuition-Microservice
tuition:
  baseUrl: http://${API_GW_HOST:localhost}:${API_GW_PORT:8080}/ignite-tuition-service
  removeStudentUrl: /api/v1/tuition/remove/student/{studentId}/tuition/{tuitionId}

## Auth-Microservice
auth:
  baseUrl: http://${API_GW_HOST:localhost}:${API_GW_PORT:8080}/ignite-auth-service
  createUserUrl: /api/v1/auth/users/register
  deleteUserUrl: /api/v1/auth/users/delete/{username}
